package test_java;

import java.io.IOException;

public class ExceptionThrow1 
{
  public void throw1() throws Exception
  {
	  System.out.println("ExceptionThrow1 this is the first one" );
	 
	  
  }
  
}
